apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 1   # You can increase later for scaling
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: nileshdgaikwad8805/wisecow:latest   # replace with DockerHub image when pushing
          ports:
            - containerPort: 4499
