name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # runs when code is pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build and push Docker image
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nileshdgaikwad8805/wisecow:latest
